### ISSUE TITLE
timer display/view

### ISSUE THREAD

**Issue by MonCaptain** [MCF-x-Course-Hero/pomodoro-timer#6]
The timer and buttons should be centered similarly to the screenshot. It should also utilize a similar color methodology.

![unknown.png](https://images.zenhubusercontent.com/62c605bb8936233603b91bd7/fa6e3d74-758c-4287-8ec4-3da616412a0f)

**Comment by ShehabMohsen** [comment]
![unknown.png](https://images.zenhubusercontent.com/62c605bb8936233603b91bd7/fa6e3d74-758c-4287-8ec4-3da616412a0f)
